Repository android/plaid, pull requests merged in 2019-01, with the labels that each got.

#585 [Bug fix] Feed is not updated when changing filters
  core/src/main/java/io/plaidapp/core/dagger/FilterAdapterModule.kt
  core/src/main/java/io/plaidapp/core/ui/FilterAdapter.kt
Labels: Ready for review, cla: yes

#587 [Bug fix] Save filter doesn't work.
  search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
Labels: Ready for review, cla: yes

#590 Update README to reflect required AS version
  README.md
Labels: cla: yes

#591 Moves the preparing of PlaidItems for display from the FeedAdapter to…
  app/src/main/java/io/plaidapp/ui/HomeActivity.java
  core/src/main/java/io/plaidapp/core/ui/FeedAdapter.java
  core/src/main/java/io/plaidapp/core/ui/PlaidItemsListExtension.kt
  search/src/main/java/io/plaidapp/search/ui/SearchActivity.kt
Labels: Ready for review, cla: yes

#592 Removing the reference to the context from FilterAdapter
  app/src/main/java/io/plaidapp/dagger/Injector.kt
  core/src/main/java/io/plaidapp/core/dagger/FilterAdapterModule.kt
  core/src/main/java/io/plaidapp/core/ui/filter/FilterAdapter.kt
  search/src/main/java/io/plaidapp/search/dagger/Injector.kt
Labels: Ready for review, cla: yes

#597 Converts ClientAuthInterceptor to Kotlin
  core/src/main/java/io/plaidapp/core/designernews/data/api/ClientAuthInterceptor.java
  core/src/main/java/io/plaidapp/core/designernews/data/api/ClientAuthInterceptor.kt
Labels: Ready for review, cla: yes

#601 Updated the readme to contain up for grabs
  README.md
Labels: Ready for review 👀, cla: yes

#608 Update to latest versions of dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: cla: yes
